---
apiVersion: v1beta1
kind: Kustomization

namespace: theatre-system
namePrefix: theatre-

commonLabels:
  app: theatre

resources:
  - ../crds/rbac_v1alpha1_directoryrolebindings.yaml
  - ../crds/workloads_v1alpha1_consoles.yaml
  - ../managers/namespace.yaml
  - ../managers/rbac.yaml
  - ../managers/workloads.yaml

secretGenerator:
  - commands:
      # Assuming the current GOOGLE_APPLICATION_CREDENTIALS env var points at
      # the key we want to use during deployment.
      credentials.json: kubectl -n theatre-system get secret theatre-google-application-credentials -o json | jq '.data."credentials.json"' -r | base64 --decode
    name: google-application-credentials
