---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: theatre-system
namePrefix: theatre-

commonLabels:
  app: theatre

resources:
  - crds/rbac_v1alpha1_directoryrolebinding.yaml
  - crds/workloads_v1alpha1_console.yaml
  - crds/workloads_v1alpha1_consoletemplate.yaml
  - managers/namespace.yaml
  - managers/rbac.yaml
  - managers/vault.yaml
  - managers/workloads.yaml
