# View goreleaser docs for configuration settings
# https://goreleaser.com

---
project_name: theatre

builds:
  - binary: theatre-consoles
    id: "theatre-consoles"
    main: cmd/theatre-consoles/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X main.Version={{.Version}}
      -X main.Commit={{.Commit}}
      -X main.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

  - binary: theatre-envconsul
    id: "theatre-envconsul"
    main: cmd/theatre-envconsul/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X main.Version={{.Version}}
      -X main.Commit={{.Commit}}
      -X main.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

  - binary: vault-manager
    id: "vault-manager"
    main: cmd/vault-manager/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X main.Version={{.Version}}
      -X main.Commit={{.Commit}}
      -X main.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

  - binary: workloads-manager
    id: "workloads-manager"
    main: cmd/workloads-manager/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X main.Version={{.Version}}
      -X main.Commit={{.Commit}}
      -X main.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

brew:
  github:
    owner: gocardless
    name: homebrew-taps
  commit_author:
    name: GoCardless Engineering
    email: engineering@gocardless.com
  # This causes downloads of this formula to be authenticated with homebrew
  # environment tokens.
  custom_require: ../lib/gc/github_private_release_download_strategy
  download_strategy: Gc::GithubPrivateReleaseDownloadStrategy
  folder: Formula
  homepage: https://github.com/gocardless/theatre
  description: GoCardless' collection of Kubernetes extensions
  test: system "#{bin}/theatre-consoles --version"
  install: |
    bin.install "theatre-consoles"
    bin.install "theatre-envconsul"
    bin.install "vault-manager"
    bin.install "workloads-manager"
