# We need to configure the networking of our kind cluster in order to expose the
# api server to containers running within Kind. Without explicitly listining on
# 0.0.0.0, any pod attempting to communicate with the api-server will resolve a
# https://localhost:<port> address, which won't be the same interface as the
# control-plane host.
#
# Our vault acceptance tests require api-server access for token reviews.
---
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
networking:
  apiServerAddress: 0.0.0.0
  apiServerPort: 19090
nodes:
  - role: control-plane
    extraPortMappings:
      # Expose the Vault service, so we can talk to it locally
      - containerPort: 32000
        hostPort: 8200
        protocol: tcp
