---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - rbac.lawrjone.xyz
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manager
spec:
  selector:
    matchLabels:
      name: manager
  template:
    metadata:
      name: manager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - command:
            - /manager
          image: gcr.io/lawrjone/theatre:latest
          imagePullPolicy: Always
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
