---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: manager
          image: theatre:latest
          imagePullPolicy: Never
          args:
            - --no-google  # disable Google for acceptance tests
