apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: consoletemplates.workloads.crd.gocardless.com
spec:
  group: workloads.crd.gocardless.com
  names:
    kind: ConsoleTemplate
    plural: consoletemplates
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalAttachSubjects:
              items:
                type: object
              type: array
            defaultTimeoutSeconds:
              format: int64
              type: integer
            maxTimeoutSeconds:
              format: int64
              type: integer
            template:
              type: object
            user:
              type: string
          required:
            - user
            - template
            - defaultTimeoutSeconds
            - maxTimeoutSeconds
            - additionalAttachSubjects
          type: object
      required:
        - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
