apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: consoles.workloads.crd.gocardless.com
spec:
  group: workloads.crd.gocardless.com
  names:
    kind: Console
    plural: consoles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            command:
              description:
                The command and arguments to execute. If not specified
                the command from the template specification will be used.
              items:
                type: string
              type: array
            consoleTemplateRef:
              type: object
            reason:
              type: string
            timeoutSeconds:
              description:
                Number of seconds that the console should run for. If the
                process running within the console has not exited before this timeout
                is reached, then the console will be terminated. If this value exceeds
                the Maximum Timeout Seconds specified in the ConsoleTemplate that
                this console refers to, then this timeout will be clamped to that
                value. Maximum value of 1 week (as per ConsoleTemplate.Spec.MaxTimeoutSeconds).
              format: int64
              maximum: 604800
              minimum: 0
              type: integer
            ttlSecondsAfterFinished:
              description:
                Specifies the TTL for this Console. The Console will be
                eligible for garbage collection ConsoleTTLSecondsAfterFinished seconds
                after it enters the Stopped phase. This field is modeled on the TTL
                mechanism in Kubernetes 1.12.
              format: int32
              maximum: 604800
              minimum: 0
              type: integer
            user:
              type: string
          required:
            - user
            - reason
            - consoleTemplateRef
          type: object
        status:
          properties:
            expiryTime:
              format: date-time
              type: string
            phase:
              type: string
            podName:
              type: string
          required:
            - podName
            - phase
          type: object
      required:
        - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
