---
version: 2

references:
  docker_golang: &docker_golang
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/lawrencejones/theatre

jobs:
  unit-integration:
    <<: *docker_golang
    steps:
      - checkout
      - run:
          name: Install Kubebuilder test helpers
          command: |
            mkdir /usr/local/kubebuilder
            curl -fsL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.7/kubebuilder_1.0.7_linux_amd64.tar.gz \
              | tar -xvz --strip=1 -C /usr/local/kubebuilder
      - run:
          name: Run tests
          command: go test -race -count=1 -v ./...

  build:
    <<: *docker_golang
    steps:
      - checkout
      - run:
          name: Build test binaries
          command: make bin/manager.linux_amd64 bin/acceptance
      - persist_to_workspace:
          root: /go/src/github.com/lawrencejones/theatre
          paths: ['bin/manager.linux_amd64', 'bin/acceptance']

  acceptance:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Install tooling
          command: |
            sudo bash <<EOF
            curl -fsL -o /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/0.0.1/kind-linux-amd64
            curl -fsL -o /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.11/kustomize_1.0.11_linux_amd64
            curl -fsL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.12/bin/linux/amd64/kubectl

            chmod a+x /usr/local/bin/kustomize /usr/local/bin/kubectl /usr/local/bin/kind
            EOF
      - run:
          name: Prepare the cluster
          command: workspace/bin/acceptance prepare --manager-binary workspace/bin/manager.linux_amd64
      - run:
          name: Run acceptance tests
          command: workspace/bin/acceptance run

workflows:
  version: 2
  build-integration:
    jobs:
      - unit-integration
      - build
      - acceptance:
          requires: [build]
