# permissions for end users to edit directoryrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directoryrolebinding-editor-role
rules:
- apiGroups:
  - rbac.crd.gocardless.com
  resources:
  - directoryrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.crd.gocardless.com
  resources:
  - directoryrolebindings/status
  verbs:
  - get
