---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: istio-manager
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: manager
          image: theatre:latest
          imagePullPolicy: Never
