---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rbac-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          image: theatre:latest
          imagePullPolicy: Never
          args:
            - --no-google  # disable Google for acceptance tests
