---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          image: theatre:latest
          imagePullPolicy: Never
