apiVersion: workloads.crd.gocardless.com/v1alpha1
kind: ConsoleTemplate
metadata:
  name: sample
  labels:
    name: sample
spec:
  defaultTimeoutSeconds: 3600
  maxTimeoutSeconds: 604800
  authorisationRules:
    - name: shell
      matchCommandElements: ["sh"]
      authorisationsRequired: 0
      subjects: []
  defaultAuthorisationRule:
    authorisationsRequired: 1
    subjects:
      - kind: Group
        name: team@example.com
  template:
    spec:
      containers:
        - name: app
          image: alpine
