---
kind: ConsoleTemplate
apiVersion: workloads.crd.gocardless.com/v1alpha1
spec:
  additionalAttachSubjects:
    - kind: User
      name: foo@example.com
    - kind: User
      name: bar@example.com
  defaultTimeoutSeconds: 300
  maxTimeoutSeconds: 300
  defaultTtlSecondsAfterFinished: 30
  defaultTtlSecondsBeforeRunning: 120
  authorisationRules:
    - name: bad-command
      matchCommandElements: ["echo", "something-bad", "**"]
      authorisationsRequired: 1
      subjects:
        - kind: User
          name: bob@example.com
  defaultAuthorisationRule:
    subjects: []
    authorisationsRequired: 0
  template:
    spec:
      containers:
        - image: alpine:latest
          name: container-name-0
          command:
            - sleep
          args:
            - "100"
metadata:
  name: console-template-0
  labels:
    repo: myapp-owner-myapp-repo
    environment: myapp-env
