---
apiVersion: rbac.gocardless.io/v1alpha1
kind: DirectoryRoleBinding
metadata:
  name: platform-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tiller
subjects:
  - kind: GoogleGroup
    name: platform@gocardless.com
  - kind: User
    name: ivan@gocardless.com
