apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: consoletemplates.workloads.crd.gocardless.com
spec:
  group: workloads.crd.gocardless.com
  names:
    kind: ConsoleTemplate
    plural: consoletemplates
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalAttachSubjects:
              items:
                type: object
              type: array
            authorisationRules:
              description:
                List of authorisation rules to match against in order from
                top to bottom.
              items:
                properties:
                  authorisationsRequired:
                    description:
                      The number of authorisations required from members
                      of the subjects before the console can run.
                    format: int64
                    type: integer
                  matchCommand:
                    description:
                      The match expression to compare to the command and
                      arguments of the console. Uses the glob format https://github.com/gobwas/glob.
                    type: string
                  name:
                    description:
                      Human readable name of authorisation rule added to
                      logs for auditing.
                    type: string
                  subjects:
                    description:
                      List of subjects that can provide authorisation for
                      the console command to run.
                    items:
                      type: object
                    type: array
                required:
                  - name
                  - matchCommand
                  - authorisationsRequired
                  - subjects
                type: object
              type: array
            defaultAuthorisationRule:
              description:
                Default authorisation rule to use if no authorisation rules
                are defined or no authorisation rules match.
              properties:
                authorisationsRequired:
                  description:
                    The number of authorisations required from members
                    of the subjects before the console can run.
                  format: int64
                  type: integer
                subjects:
                  description:
                    List of subjects that can provide authorisation for
                    the console command to run.
                  items:
                    type: object
                  type: array
              required:
                - authorisationsRequired
                - subjects
              type: object
            defaultTimeoutSeconds:
              description:
                Default time, in seconds, that a Console will be created
                for. Maximum value of 1 week (as per MaxTimeoutSeconds).
              format: int64
              maximum: 604800
              minimum: 0
              type: integer
            defaultTtlSecondsAfterFinished:
              description:
                Specifies the TTL for any Console created with this template.
                If set, the Console will be eligible for garbage collection ConsoleTTLSecondsAfterFinished
                seconds after it enters the Stopped phase. If not set, this value
                defaults to 24 hours. This field is modeled closely on the TTL mechanism
                in Kubernetes 1.12.
              format: int32
              maximum: 604800
              minimum: 0
              type: integer
            maxTimeoutSeconds:
              description:
                Maximum time, in seconds, that a Console can be created
                for. Maximum value of 1 week.
              format: int64
              maximum: 604800
              minimum: 0
              type: integer
            template:
              type: object
          required:
            - template
            - defaultTimeoutSeconds
            - maxTimeoutSeconds
          type: object
      required:
        - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
