---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

imageTags:
  - name: eu.gcr.io/gc-containers/gocardless/theatre
    newTag: 5363f91a397364af056269a1d90ddaa2a495b581
