---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

imageTags:
  - name: eu.gcr.io/gc-containers/gocardless/theatre
    newTag: d2d3a1ef396703981dfdde08dd0632a8313784c1
